const countries = [
  {"name": "Choose your option..."},
  {"name": "Afghanistan", "value": "Afghanistan"},
  {"name": "Albania", "value": "Albania"},
  {"name": "Algeria", "value": "Algeria"},
  {"name": "Argentina", "value": "Argentina"},
  {"name": "Australia", "value": "Australia"},
  {"name": "Austria", "value": "Austria"},
  {"name": "Bahrain", "value": "Bahrain"},
  {"name": "Bangladesh", "value": "Bangladesh"},
  {"name": "Belgium", "value": "Belgium"},
  {"name": "Bolivia", "value": "Bolivia"},
  {"name": "Brazil", "value": "Brazil"},
  {"name": "Canada", "value": "Canada"},
  {"name": "Chile", "value": "Chile"},
  {"name": "China", "value": "China"},
  {"name": "Colombia", "value": "Colombia"},
  {"name": "Costa Rica", "value": "Costa Rica"},
  {"name": "Czech Republic", "value": "Czech Republic"},
  {"name": "Denmark", "value": "Denmark"},
  {"name": "Ecuador", "value": "Ecuador"},
  {"name": "Egypt", "value": "Egypt"},
  {"name": "El Salvador", "value": "El Salvador"},
  {"name": "Ethiopia", "value": "Ethiopia"},
  {"name": "Finland", "value": "Finland"},
  {"name": "France", "value": "France"},
  {"name": "Germany", "value": "Germany"},
  {"name": "Greece", "value": "Greece"},
  {"name": "Guatemala", "value": "Guatemala"},
  {"name": "Honduras", "value": "Honduras"},
  {"name": "Hungary", "value": "Hungary"},
  {"name": "India", "value": "India"},
  {"name": "Indonesia", "value": "Indonesia"},
  {"name": "Iran", "value": "Iran"},
  {"name": "Iraq", "value": "Iraq"},
  {"name": "Ireland", "value": "Ireland"},
  {"name": "Israel", "value": "Israel"},
  {"name": "Italy", "value": "Italy"},
  {"name": "Japan", "value": "Japan"},
  {"name": "Jordan", "value": "Jordan"},
  {"name": "Kazakhstan", "value": "Kazakhstan"},
  {"name": "Kenya", "value": "Kenya"},
  {"name": "Kuwait", "value": "Kuwait"},
  {"name": "Lebanon", "value": "Lebanon"},
  {"name": "Libya", "value": "Libya"},
  {"name": "Malaysia", "value": "Malaysia"},
  {"name": "Mexico", "value": "Mexico"},
  {"name": "Morocco", "value": "Morocco"},
  {"name": "Nepal", "value": "Nepal"},
  {"name": "Netherlands", "value": "Netherlands"},
  {"name": "New Zealand", "value": "New Zealand"},
  {"name": "Nigeria", "value": "Nigeria"},
  {"name": "Norway", "value": "Norway"},
  {"name": "Oman", "value": "Oman"},
  {"name": "Pakistan", "value": "Pakistan"},
  {"name": "Panama", "value": "Panama"},
  {"name": "Paraguay", "value": "Paraguay"},
  {"name": "Peru", "value": "Peru"},
  {"name": "Philippines", "value": "Philippines"},
  {"name": "Poland", "value": "Poland"},
  {"name": "Portugal", "value": "Portugal"},
  {"name": "Qatar", "value": "Qatar"},
  {"name": "Russia", "value": "Russia"},
  {"name": "Saudi Arabia", "value": "Saudi Arabia"},
  {"name": "Singapore", "value": "Singapore"},
  {"name": "South Africa", "value": "South Africa"},
  {"name": "South Korea", "value": "South Korea"},
  {"name": "Spain", "value": "Spain"},
  {"name": "Sudan", "value": "Sudan"},
  {"name": "Sweden", "value": "Sweden"},
  {"name": "Switzerland", "value": "Switzerland"},
  {"name": "Syria", "value": "Syria"},
  {"name": "Taiwan", "value": "Taiwan"},
  {"name": "Tanzania", "value": "Tanzania"},
  {"name": "Thailand", "value": "Thailand"},
  {"name": "Turkey", "value": "Turkey"},
  {"name": "Uganda", "value": "Uganda"},
  {"name": "Ukraine", "value": "Ukraine"},
  {"name": "United Arab Emirates", "value": "United Arab Emirates"},
  {"name": "United Kingdom", "value": "United Kingdom"},
  {"name": "United States", "value": "United States"},
  {"name": "Vietnam", "value": "Vietnam"},
  {"name": "Yemen", "value": "Yemen"}
]

export default countries